builds:
  - main: main.go
    binary: TestGoReleaser
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: mac0S
    linux: Tux
  files:
    - extraFile.txt

env_files:
  github_token: ~/Documents/Github/TOKENZ/forGoRelease

