# .travis.yml
language: go
go: "1.10"


# calls goreleaser
# deploy:
# - provider: script
#   skip_cleanup: true
#   script: curl -sL http://git.io/goreleaser | bash
#   on:
#     tags: true
#     condition: $TRAVIS_OS_NAME = linux


# before_deploy:
#   - export OS_TARGETS="linux darwin windows"
#   - export ARCH_TARGETS="arm amd64"
#   - export GOARM="6"
#   - go get github.com/mitchellh/gox
#   - gox -os "$OS_TARGETS" -arch="$ARCH_TARGETS"

# global: 

# env:
#   - GOOS=windows  GOARCH=amd64
#   - GOOS=darwin   GOARCH=amd64
#   - GOOS=linux    GOARCH=amd64
#   - GOOS=linux    GOARCH=arm      GOARM=7
#   - GOOS=linux    GOARCH=arm      GOARM=6

# before_deploy:
#    - go get github.com/mitchellh/gox
#    - gox 



before_deploy:
  - git config --local user.name $GITHUB_USER
  - git config --local user.email $GITHUB_EMAIL
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - chmod +x /scripts/manybuild.sh
  - ./scripts/manybuild.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  skip_cleanup: true
  file: releases/*
  on:
    condition: $TRAVIS_OS_NAME = linux