# .travis.yml
language: go
go:
  - "1.10"

before_install:
  - go get github.com/goreleaser/goreleaser

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: goreleaser
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux